### ISSUE TITLE
Running CoGAN

### ISSUE THREAD

**Issue by mmosquera10** [mingyuliutw/CoGAN#5]
Hello,

I am trying to run the code. Can you please tell me how to run this and specify any dependencies? There was no README file included with the code.

Thank You,
Maria

**Comment by mingyuliutw** [comment]
https://github.com/mingyuliutw/CoGAN/blob/master/README.md ?

**Comment by mmosquera10** [comment]
Sorry about that. For some reason I did not see it. 
I have an issue running the code for Pytorch. I am trying to run the simple example:
cd cogan_pytorch/src;
python train_cogan_mnistedge.py --config ../exps/mnistedge_cogan.yaml;

However, I get the following output and error:
 python train_cogan_mnistedge.py --config ../exps/mnistedge_cogan.yaml
self.scale=2.0
self.log='../outputs/mnistedge_cogan/mnistedge_cogan.log'
self.snapshot_prefix='../outputs/mnistedge_cogan/mnistedge_cogan'
self.max_iter=5000
self.batch_size=64
self.bias=0.5
self.latent_dims=100
self.snapshot_iter=500
self.display=10
<net_config.NetConfig object at 0x7fd9cd2def90>
Traceback (most recent call last):
  File "train_cogan_mnistedge.py", line 95, in <module>
    main(sys.argv)
  File "train_cogan_mnistedge.py", line 35, in main
    os.remove(config.log)
OSError: [Errno 21] Is a directory: '../outputs/mnistedge_cogan/mnistedge_cogan.log'

Any help would be greatly appreciated! Thanks!

**Comment by ybZhao1119** [comment]
i have the same question with the above  ，can you tell me how to solve the problem？

Any help would be greatly appreciated！Thanks！

**Comment by sandhyalaxmiK** [comment]
if the directory is empty, you have to use, os.remove().
If the directory contains files, then, use
import shutil 
shutil.rmtree(config.log)
