### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by mmosquera10** [mingyuliutw/CoGAN#6]
Hello,

I have an issue running the code for Pytorch. I am trying to run the simple example:
cd cogan_pytorch/src;
python train_cogan_mnistedge.py --config ../exps/mnistedge_cogan.yaml;

However, I get the following output and error:
python train_cogan_mnistedge.py --config ../exps/mnistedge_cogan.yaml
self.scale=2.0
self.log='../outputs/mnistedge_cogan/mnistedge_cogan.log'
self.snapshot_prefix='../outputs/mnistedge_cogan/mnistedge_cogan'
self.max_iter=5000
self.batch_size=64
self.bias=0.5
self.latent_dims=100
self.snapshot_iter=500
self.display=10
<net_config.NetConfig object at 0x7fd9cd2def90>
Traceback (most recent call last):
File "train_cogan_mnistedge.py", line 95, in 
main(sys.argv)
File "train_cogan_mnistedge.py", line 35, in main
os.remove(config.log)
OSError: [Errno 21] Is a directory: '../outputs/mnistedge_cogan/mnistedge_cogan.log'

Any help would be greatly appreciated! Thanks!

**Comment by Ellenisawake** [comment]
Just remove the line to run it...
Have you successfully finished training? Seems no luck for me to get it work. With all the original settings as provided in the code, the training just won't converge.
